### ISSUE TITLE
Xdagpool installation request help

### ISSUE THREAD

**Issue by mot2017** [kbs1/openxdagpool-scripts#1]
Hello, install xdagpool, do you need to install openxdagpool-scripts first?

**Comment by kbs1** [comment]
Hello, yes, openxdagpool uses openxdagpool-scripts, so you need to install them first.

**Comment by fabius8** [comment]
Hi,kbs1. I find it can't get response from other node. Do i need change the peer address?
![image](https://user-images.githubusercontent.com/9312696/41150732-4cb3dcdc-6b41-11e8-96f1-b9ccd5662d07.png)

**Comment by kbs1** [comment]
Hi, are you whitelisted on the network?

**Comment by fabius8** [comment]
No，I think not， where can i join the whitelist？

**Comment by kbs1** [comment]
Please visit the discord group for more information (see https://discord.gg/zT7DW2N)
