### ISSUE TITLE
Error while running openxdagpool

### ISSUE THREAD

**Issue by mrsaicharan1** [kbs1/openxdagpool-scripts#3]
When I execute` php artisan data:live ` in the directory `/var/www/openxdagpool`. Gives error **unable to call openxdagpool-scripts core**

**Comment by kbs1** [comment]
try to call the core using wget, it's probably not configured correctly.

**Comment by mrsaicharan1** [comment]
Wait what do you mean by calling it via wget..It's used for downloads right? (Sorry for the duplicate.Please attend to this issue here)

**Comment by kbs1** [comment]
new readme at https://github.com/XDagger/openxdagpool-scripts. This issue is the same as https://github.com/XDagger/openxdagpool/issues/4.

**Comment by mrsaicharan1** [comment]
Yeah,will try it out and perform the new instructions. Also, when I try to gather the blocks it says that the node is unavailable. Is it because my IP isn't whitelisted yet?

**Comment by kbs1** [comment]
Yes, you have to be whitelisted.
